### ISSUE TITLE
Scrub is not scrubbing 

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/scrub#2]
Testing scrub on legend after a few remarks about trouble with it in the LNbits TG group.

Originally wanted to send via split to a wallet and do a scrub from there to a lnaddress (lntipbot), which didnt work. neither to a LNURLp on the same or another instance.

Also tested direct payments to the Scrub-Wallet as well by paying an invoice - also no scrub.

**Comment by dergigi** [comment]
Can confirm. Not working for me on legends, also not working on my own instance (lnbits commit `c81d3e06c8c4217c1c38a71e24964df0e7b80d2c`).

**Comment by dni** [comment]
ok, scrubbing works in fakewallet locally for me, it maybe related the a issue that pops up with core lightning right now.  https://github.com/lnbits/lnbits/issues/1565

**Comment by dergigi** [comment]
It works sometimes and sometimes it doesn't, not sure why or how to best debug this. The wallets are well funded, so a lack of funds to pay fees is not it. 

I thought it had something to do with multi-path payments, but that was also not it, as both MP and AMP work sometimes. But sometimes, scrubbing fails. Hmm 🤔

**Comment by xannythepleb** [comment]
+1 here it doesn't work for me either. Using LNTipBot as the backend so I don't think it's an LND issue (iirc, LNTips uses LNBits as a backend itself).

**Comment by ulrichard** [comment]
Doesn't work at all for me. 
lnbits instance on https://timecatcher.lnbits.de
scrub target on https://card.swiss-bitcoin-pay.ch/

**Comment by talvasconcelos** [comment]
Can this be related to Lightning Network routing issues?

**Comment by ulrichard** [comment]
Manually sending to the same destination always works, so it's unlikely to be network routing related.

**Comment by arbadacarbaYK** [comment]
> Doesn't work at all for me. lnbits instance on https://timecatcher.lnbits.de scrub target on https://card.swiss-bitcoin-pay.ch/

You have to make sure that theres smth left over for the fees e.g. by adding satsto the wallet before the first scrub is defined. 

 
<img width="662" alt="Bildschirmfoto 2023-08-30 um 18 28 03" src="https://github.com/lnbits/scrub/assets/63317640/082d2d8f-3f4d-4635-a794-47b1b222eeeb">

**Comment by MichaelAntonFischer** [comment]
Related to this issue on split, a periodic rerun would be great:
https://github.com/lnbits/splitpayments/issues/10

**Comment by dni** [comment]
i noted this for splits aswell. 
maybe a scrub log, with all scrubs would make the failing scrubs more comprehensible and there could be a feature to manually rerun them

**Comment by MichaelAntonFischer** [comment]
As mentioned on Splits, for me an optional setting to periodically rescrub the wallet-balance sub fee reserve is the way to go.

the whole point about split and scrub is that it’s automatic. Right now I need to periodically send Sats to a different wallet and back again manually to retrigger.

**Comment by ulrichard** [comment]
It miraculously started working two weeks ago. I assume the operator of timecatcher.lnbits.de updated something.
